### ISSUE TITLE
The guitar tuner downloaded from releases don't work

### ISSUE THREAD

**Issue by DetErDugget** [Macabresoft/GuitarTuner#1]
When i start it up, my curser spin loads for a bit, and then the app shuts down again :( 

Tried both x64 and x86 win versions

**Comment by DetErDugget** [comment]
And thanks for sharing ur work with us for free! :D

**Comment by macabrett** [comment]
Apologies, I missed this message. Unfortunately, I never fully finished this project. Parts of it had worked for a bit, but I've abandoned it.

You may or may not be interested in a web based guitar tuner I created:
- https://github.com/Macabresoft/guitar-tuner
- https://www.macabresoft.com/guitar-tuner/

It's not feature rich, but it gets the job done in a pinch.

I'll update the README in this project and archive it, but anyone reading this can feel free to fork it. The most useful code in the solution is probably the SampleAnalyzer .GetBufferInformation code, as it uses the Average Magnitude Difference Function to determine the frequency of an audio buffer.
